[[redirects]]
  from = "/product-docs/6.2/*"
  to = "/product-docs/6.2/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/product-docs/*"
  to = "/product-docs/6.3/:splat"
  status = 301
  force = true